using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class TblBinhLuan
    {
        public string HoNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public DateTime ThoiGian { get; set; }
    }
    /// <summary>
    /// Controller class for TblBinhLuan
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblBinhLuanController
    {
        // Preload our schema..
        TblBinhLuan thisSchemaLoad = new TblBinhLuan();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblBinhLuanCollection FetchAll()
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection();
            Query qry = new Query(TblBinhLuan.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBinhLuanCollection FetchByID(object Id)
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBinhLuanCollection FetchByQuery(Query qry)
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblBinhLuan.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblBinhLuan.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblBinhLuan Insert(TblBinhLuan item)
	    {
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblBinhLuan Update(TblBinhLuan item)
	    {
            item.Save(UserName);
            return item;
        }
    }
}
