using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class TblThongBao
    {
        public string HoNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string TenMauThongBao { get; set; }
        public string TenVanPhong { get; set; }
        public string HoTen { get; set; }
    }
    /// <summary>
    /// Controller class for TblThongBao
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblThongBaoController
    {
        // Preload our schema..
        TblThongBao thisSchemaLoad = new TblThongBao();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblThongBaoCollection FetchAll()
        {
            TblThongBaoCollection coll = new TblThongBaoCollection();
            Query qry = new Query(TblThongBao.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThongBaoCollection FetchByID(object Id)
        {
            TblThongBaoCollection coll = new TblThongBaoCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThongBaoCollection FetchByQuery(Query qry)
        {
            TblThongBaoCollection coll = new TblThongBaoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblThongBao.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblThongBao.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblThongBao Insert(TblThongBao item)
	    {
            item.Save(UserName);
            return item;
        }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblThongBao Update(TblThongBao item)
	    {
            item.Save(UserName);
            return item;

        }
    }
}
