using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for TblBinhLuan
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblBinhLuanController
    {
        // Preload our schema..
        TblBinhLuan thisSchemaLoad = new TblBinhLuan();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblBinhLuanCollection FetchAll()
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection();
            Query qry = new Query(TblBinhLuan.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBinhLuanCollection FetchByID(object Id)
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBinhLuanCollection FetchByQuery(Query qry)
        {
            TblBinhLuanCollection coll = new TblBinhLuanCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblBinhLuan.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblBinhLuan.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,Guid IdNguoiBinhLuan,string NoiDung,Guid IdThongBao,Guid? IdBinhLuan,string TrangThai,DateTime NgayTao,DateTime? NgayCapNhat)
	    {
		    TblBinhLuan item = new TblBinhLuan();
		    
            item.Id = Id;
            
            item.IdNguoiBinhLuan = IdNguoiBinhLuan;
            
            item.NoiDung = NoiDung;
            
            item.IdThongBao = IdThongBao;
            
            item.IdBinhLuan = IdBinhLuan;
            
            item.TrangThai = TrangThai;
            
            item.NgayTao = NgayTao;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,Guid IdNguoiBinhLuan,string NoiDung,Guid IdThongBao,Guid? IdBinhLuan,string TrangThai,DateTime NgayTao,DateTime? NgayCapNhat)
	    {
		    TblBinhLuan item = new TblBinhLuan();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.IdNguoiBinhLuan = IdNguoiBinhLuan;
				
			item.NoiDung = NoiDung;
				
			item.IdThongBao = IdThongBao;
				
			item.IdBinhLuan = IdBinhLuan;
				
			item.TrangThai = TrangThai;
				
			item.NgayTao = NgayTao;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
