using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the TblNguoiDung class.
	/// </summary>
    [Serializable]
	public partial class TblNguoiDungCollection : ActiveList<TblNguoiDung, TblNguoiDungCollection>
	{	   
		public TblNguoiDungCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblNguoiDungCollection</returns>
		public TblNguoiDungCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblNguoiDung o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblNguoiDung table.
	/// </summary>
	[Serializable]
	public partial class TblNguoiDung : ActiveRecord<TblNguoiDung>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblNguoiDung()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblNguoiDung(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblNguoiDung(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblNguoiDung(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblNguoiDung", TableType.Table, DataService.GetInstance("ViewWeb"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarIdNhanVien = new TableSchema.TableColumn(schema);
				colvarIdNhanVien.ColumnName = "IdNhanVien";
				colvarIdNhanVien.DataType = DbType.Guid;
				colvarIdNhanVien.MaxLength = 0;
				colvarIdNhanVien.AutoIncrement = false;
				colvarIdNhanVien.IsNullable = false;
				colvarIdNhanVien.IsPrimaryKey = false;
				colvarIdNhanVien.IsForeignKey = true;
				colvarIdNhanVien.IsReadOnly = false;
				colvarIdNhanVien.DefaultSetting = @"";
				
					colvarIdNhanVien.ForeignKeyTableName = "TblNhanVien";
				schema.Columns.Add(colvarIdNhanVien);
				
				TableSchema.TableColumn colvarTenDangNhap = new TableSchema.TableColumn(schema);
				colvarTenDangNhap.ColumnName = "TenDangNhap";
				colvarTenDangNhap.DataType = DbType.AnsiString;
				colvarTenDangNhap.MaxLength = 20;
				colvarTenDangNhap.AutoIncrement = false;
				colvarTenDangNhap.IsNullable = false;
				colvarTenDangNhap.IsPrimaryKey = false;
				colvarTenDangNhap.IsForeignKey = false;
				colvarTenDangNhap.IsReadOnly = false;
				colvarTenDangNhap.DefaultSetting = @"";
				colvarTenDangNhap.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenDangNhap);
				
				TableSchema.TableColumn colvarPass = new TableSchema.TableColumn(schema);
				colvarPass.ColumnName = "Pass";
				colvarPass.DataType = DbType.AnsiString;
				colvarPass.MaxLength = 20;
				colvarPass.AutoIncrement = false;
				colvarPass.IsNullable = false;
				colvarPass.IsPrimaryKey = false;
				colvarPass.IsForeignKey = false;
				colvarPass.IsReadOnly = false;
				colvarPass.DefaultSetting = @"";
				colvarPass.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPass);
				
				TableSchema.TableColumn colvarKichHoat = new TableSchema.TableColumn(schema);
				colvarKichHoat.ColumnName = "KichHoat";
				colvarKichHoat.DataType = DbType.Boolean;
				colvarKichHoat.MaxLength = 0;
				colvarKichHoat.AutoIncrement = false;
				colvarKichHoat.IsNullable = false;
				colvarKichHoat.IsPrimaryKey = false;
				colvarKichHoat.IsForeignKey = false;
				colvarKichHoat.IsReadOnly = false;
				colvarKichHoat.DefaultSetting = @"";
				colvarKichHoat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarKichHoat);
				
				TableSchema.TableColumn colvarIdVaiTro = new TableSchema.TableColumn(schema);
				colvarIdVaiTro.ColumnName = "IdVaiTro";
				colvarIdVaiTro.DataType = DbType.Guid;
				colvarIdVaiTro.MaxLength = 0;
				colvarIdVaiTro.AutoIncrement = false;
				colvarIdVaiTro.IsNullable = false;
				colvarIdVaiTro.IsPrimaryKey = false;
				colvarIdVaiTro.IsForeignKey = true;
				colvarIdVaiTro.IsReadOnly = false;
				colvarIdVaiTro.DefaultSetting = @"";
				
					colvarIdVaiTro.ForeignKeyTableName = "TblVaiTro";
				schema.Columns.Add(colvarIdVaiTro);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.Boolean;
				colvarTrangThai.MaxLength = 0;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = false;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				colvarNgayTao.DefaultSetting = @"";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 50;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 50;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["ViewWeb"].AddSchema("TblNguoiDung",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("IdNhanVien")]
		[Bindable(true)]
		public Guid IdNhanVien 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhanVien); }
			set { SetColumnValue(Columns.IdNhanVien, value); }
		}
		  
		[XmlAttribute("TenDangNhap")]
		[Bindable(true)]
		public string TenDangNhap 
		{
			get { return GetColumnValue<string>(Columns.TenDangNhap); }
			set { SetColumnValue(Columns.TenDangNhap, value); }
		}
		  
		[XmlAttribute("Pass")]
		[Bindable(true)]
		public string Pass 
		{
			get { return GetColumnValue<string>(Columns.Pass); }
			set { SetColumnValue(Columns.Pass, value); }
		}
		  
		[XmlAttribute("KichHoat")]
		[Bindable(true)]
		public bool KichHoat 
		{
			get { return GetColumnValue<bool>(Columns.KichHoat); }
			set { SetColumnValue(Columns.KichHoat, value); }
		}
		  
		[XmlAttribute("IdVaiTro")]
		[Bindable(true)]
		public Guid IdVaiTro 
		{
			get { return GetColumnValue<Guid>(Columns.IdVaiTro); }
			set { SetColumnValue(Columns.IdVaiTro, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public bool TrangThai 
		{
			get { return GetColumnValue<bool>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblNhanVien ActiveRecord object related to this TblNguoiDung
		/// 
		/// </summary>
		public Public.TblNhanVien TblNhanVien
		{
			get { return Public.TblNhanVien.FetchByID(this.IdNhanVien); }
			set { SetColumnValue("IdNhanVien", value.Id); }
		}
		
		
		/// <summary>
		/// Returns a TblVaiTro ActiveRecord object related to this TblNguoiDung
		/// 
		/// </summary>
		public Public.TblVaiTro TblVaiTro
		{
			get { return Public.TblVaiTro.FetchByID(this.IdVaiTro); }
			set { SetColumnValue("IdVaiTro", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,Guid varIdNhanVien,string varTenDangNhap,string varPass,bool varKichHoat,Guid varIdVaiTro,bool varTrangThai,DateTime varNgayTao,string varNguoiTao,DateTime? varNgayCapNhat,string varNguoiCapNhat)
		{
			TblNguoiDung item = new TblNguoiDung();
			
			item.Id = varId;
			
			item.IdNhanVien = varIdNhanVien;
			
			item.TenDangNhap = varTenDangNhap;
			
			item.Pass = varPass;
			
			item.KichHoat = varKichHoat;
			
			item.IdVaiTro = varIdVaiTro;
			
			item.TrangThai = varTrangThai;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayCapNhat = varNgayCapNhat;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,Guid varIdNhanVien,string varTenDangNhap,string varPass,bool varKichHoat,Guid varIdVaiTro,bool varTrangThai,DateTime varNgayTao,string varNguoiTao,DateTime? varNgayCapNhat,string varNguoiCapNhat)
		{
			TblNguoiDung item = new TblNguoiDung();
			
				item.Id = varId;
			
				item.IdNhanVien = varIdNhanVien;
			
				item.TenDangNhap = varTenDangNhap;
			
				item.Pass = varPass;
			
				item.KichHoat = varKichHoat;
			
				item.IdVaiTro = varIdVaiTro;
			
				item.TrangThai = varTrangThai;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayCapNhat = varNgayCapNhat;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhanVienColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn TenDangNhapColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn PassColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn KichHoatColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn IdVaiTroColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string IdNhanVien = @"IdNhanVien";
			 public static string TenDangNhap = @"TenDangNhap";
			 public static string Pass = @"Pass";
			 public static string KichHoat = @"KichHoat";
			 public static string IdVaiTro = @"IdVaiTro";
			 public static string TrangThai = @"TrangThai";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayCapNhat = @"NgayCapNhat";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
