using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for TblVanPhong
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblVanPhongController
    {
        // Preload our schema..
        TblVanPhong thisSchemaLoad = new TblVanPhong();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblVanPhongCollection FetchAll()
        {
            TblVanPhongCollection coll = new TblVanPhongCollection();
            Query qry = new Query(TblVanPhong.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVanPhongCollection FetchByID(object Id)
        {
            TblVanPhongCollection coll = new TblVanPhongCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVanPhongCollection FetchByQuery(Query qry)
        {
            TblVanPhongCollection coll = new TblVanPhongCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblVanPhong.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblVanPhong.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,string TenVanPhong,DateTime NgayTao,string NguoiTao,DateTime? NgayCapNhat,string NguoiCapNhat,bool TrangThai)
	    {
		    TblVanPhong item = new TblVanPhong();
		    
            item.Id = Id;
            
            item.TenVanPhong = TenVanPhong;
            
            item.NgayTao = NgayTao;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayCapNhat = NgayCapNhat;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.TrangThai = TrangThai;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,string TenVanPhong,DateTime NgayTao,string NguoiTao,DateTime? NgayCapNhat,string NguoiCapNhat,bool TrangThai)
	    {
		    TblVanPhong item = new TblVanPhong();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.TenVanPhong = TenVanPhong;
				
			item.NgayTao = NgayTao;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayCapNhat = NgayCapNhat;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.TrangThai = TrangThai;
				
	        item.Save(UserName);
	    }
    }
}
